### ISSUE TITLE
Feature request: Improve docks about vm_size

### ISSUE THREAD

**Issue by morallito** [hashicorp/terraform-provider-azurestack#129]
I'm starting to create my infrastructure in Azure using Terraform. In order to create a mirror from my azure account, I had created a list with all my vm sizes, founded a Azure equivalent for all the vms and checked if the vm's that i had chosen are available n  the region west us 2.

Now, that I want to create some vm's, the terraform interface is showing me that 
```
Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.
```

when I go to the Azure painel, I'm able to create the VM manually, in the same region. 

I'm trying to create a Standard_A1 VM, in west us 2.

How can I find out the rigth name for the VM in terraform? Where is the documentation about it?

**Comment by jbpaux** [comment]
It has nothing related to Azure Stack. Please use the azurerm provider and have a look at the documentation.
